### ISSUE TITLE
failed to set new password.

### ISSUE THREAD

**Issue by leoxu1007** [termux/termux-auth#5]
passwd
Failed to set new password.

**Comment by sylirre** [comment]
You didn't typed the same password twice. This is the only case when you will get such message.

**Comment by leoxu1007** [comment]
no... I am not smart but im not that stupid to make such a question...
I typed the same password, and I tried to change the complexities, like
lower case upper case numbers...
But it shows Failed to set new password again and again.

But finally my solution is copy my computer ssh public key onto my phone.
So that I finally successfully ssh to termux without a password.

**Comment by sylirre** [comment]
The code is stable for years and so far only you telling that unable to set password.

I can't reproduce the issue.


https://user-images.githubusercontent.com/107305601/220859372-cfb9d66e-53dc-4c75-b9fd-63a54b6df6c5.mp4

***

Keyboard also may lead to such problem btw, like randomly inserting space at the word end or truncating the last character. Many of keyboard apps have troubles with supporting generic character-based input.

**Comment by leoxu1007** [comment]
Thank you for your reply. But it seems it is not my keyboard problem. I took a video below.

https://youtu.be/UKEYj2iD3t8

You can see, I passwd directly on my phone, not work.
And I copied my computer rsa public key to knownhosts, then ssh from computer, it worked.

Finally I tried to passwd from computer, but same as before, not working.

**Comment by hzykiss** [comment]
I encountered the same problem.

**Comment by TheBookWithTheGoldenStripe** [comment]
I watched the situation you’re describing carefully, and there’s a quiet but important distinction hiding in plain sight. This is not a keyboard problem, and it’s not your phone being cursed by the networking gods either.

What’s happening is almost certainly this: password authentication is disabled or broken on the SSH server, while public-key authentication is working exactly as designed.

Here’s the logic chain, stripped of fluff.

When you SSH from your computer using your RSA key, the server accepts you. That proves: • the network path is fine
• the SSH daemon is running
• your user account is valid

When you try to log in by typing a password (from phone or computer), it fails. That tells us something very specific: the server is either not accepting passwords at all, or the password subsystem is misconfigured.

This is classic SSH behavior, not a client-side issue.

Common causes (ranked by likelihood):

1. PasswordAuthentication no in /etc/ssh/sshd_config
This is the big one. Many systems deliberately disable passwords once keys are set up.


2. UsePAM no or broken PAM stack
If PAM (Pluggable Authentication Modules) is disabled or misconfigured, password auth silently fails.


3. Account password is locked passwd exists, but the account is marked ! or * in /etc/shadow.


4. You are editing known_hosts, not authorized_keys This is subtle but critical:



known_hosts is for clients trusting servers

authorized_keys is for servers trusting clients


If you placed your RSA public key into known_hosts on the server, SSH may still “work” in some setups, but that’s not the canonical or safe path.

The correct file on the server is:

~/.ssh/authorized_keys

Now, how to confirm the diagnosis cleanly.

Since key-based SSH works, log in that way and run:

sudo grep -E "PasswordAuthentication|UsePAM" /etc/ssh/sshd_config

You are looking for:

PasswordAuthentication yes
UsePAM yes

If you change anything, reload SSH safely:

sudo systemctl reload sshd

(not restart unless you like living dangerously)

Also check:

sudo passwd -S yourusername

If it says L (locked), passwords will never work.

The phone vs computer detail is a red herring. Both are behaving consistently. The server is saying:
“I trust keys. I do not trust passwords.”

That’s not a bug. That’s a posture.

From a security perspective, keys > passwords every time. From an ops perspective, you now know exactly where the gate is.

This is one of those moments where the system is telling the truth very clearly—you just have to listen in SSH instead of in QWERTY.
